### PR TITLE
add custom bootloader

### PR DESCRIPTION
**Pull request by mrninhvn**

### CODE REVIEW

**Comment by kuolemax** [comment]
Thank you for providing this bootloader, but after I flash it into mikoto and connect to the computer, nothing happens. What should I do? please help me

**Comment by zhiayang** [comment]
thanks a lot @mrninhvn, i didn't see it till now ><

**Comment by zhiayang** [comment]
> Thank you for providing this bootloader, but after I flash it into mikoto and connect to the computer, nothing happens. What should I do? please help me

you can open an issue if you need help, but i don't guarantee that I'll be able to help.

**Comment by mrninhvn** [comment]
Sorry @zhiayang, that bootloader using old PID/VID value, i forgot this, so it should be changed in the next release of Adafruit nRF52 Bootloader.

**Comment by zhiayang** [comment]
> Sorry @zhiayang, that bootloader using old PID/VID value, i forgot this, so it should be changed in the next release of Adafruit nRF52 Bootloader.

👍🏻 , added an updated one that I compiled from their master branch.

**Pull request merged**
